version: '3'

volumes:
  my-datavolume:
  files-volume:

services:
  docker-mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=hotel_db
      - MYSQL_USER=${DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3307:3306

  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - files-volume:/app/images
    ports:
       - 8080:8080
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/hotel_db?allowPublicKeyRetrieval=True&autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
