version: '3'

volumes:
  my-datavolume:

services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Verystrongpw1
      - MYSQL_DATABASE=hotel_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3307:3306

  app:
    build: .
    restart: on-failure:10
    volumes:
      - ./logs:/app/logs
    ports:
       - 8080:8080
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/hotel_db?allowPublicKeyRetrieval=True&autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
