version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Verystrongpw1'
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  my-datavolume: